/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as InteractiveRpgRouteImport } from './routes/interactive-rpg'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryRpgIdRouteImport } from './routes/story-rpg.$id'
import { Route as PlaySessionIdRouteImport } from './routes/play.$sessionId'
import { Route as InteractiveRpgIdRouteImport } from './routes/interactive-rpg.$id'
import { Route as CharacterIdRouteImport } from './routes/character.$id'
import { Route as ApiUnlocksRouteImport } from './routes/api/unlocks'
import { Route as ApiStoryWritingAssistRouteImport } from './routes/api/story-writing-assist'
import { Route as ApiStoryRpgRouteImport } from './routes/api/story-rpg'
import { Route as ApiReaderStoryRouteImport } from './routes/api/reader-story'
import { Route as ApiReaderProfileImageRouteImport } from './routes/api/reader-profile-image'
import { Route as ApiMyChatCharacterRouteImport } from './routes/api/my-chat-character'
import { Route as ApiMarketplaceRouteImport } from './routes/api/marketplace'
import { Route as ApiHomePlacementsRouteImport } from './routes/api/home-placements'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCharacterChatRouteImport } from './routes/api/character-chat'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiStorageEnsureStoryMediaRouteImport } from './routes/api/storage/ensure-story-media'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiAuthStaffAccessRouteImport } from './routes/api/auth/staff-access'
import { Route as ApiAdminStoryAiRouteImport } from './routes/api/admin/story-ai'
import { Route as ApiAdminStoriesRouteImport } from './routes/api/admin/stories'
import { Route as ApiAdminStaffRouteImport } from './routes/api/admin/staff'
import { Route as ApiAdminRevenueRulesRouteImport } from './routes/api/admin/revenue-rules'
import { Route as ApiAdminPlacementsRouteImport } from './routes/api/admin/placements'
import { Route as ApiAdminMediaRouteImport } from './routes/api/admin/media'
import { Route as ApiAdminLlmProvidersRouteImport } from './routes/api/admin/llm-providers'
import { Route as ApiAdminImportSummaryRouteImport } from './routes/api/admin/import-summary'
import { Route as ApiAdminCoreRouteImport } from './routes/api/admin/core'
import { Route as AuthenticatedMarketplaceIdRouteImport } from './routes/_authenticated/marketplace.$id'
import { Route as AuthenticatedBuilderIdRouteImport } from './routes/_authenticated/builder.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStudioRouteImport } from './routes/_authenticated/admin.studio'
import { Route as AuthenticatedAdminStoryRpgRouteImport } from './routes/_authenticated/admin.story-rpg'
import { Route as AuthenticatedAdminStoriesRouteImport } from './routes/_authenticated/admin.stories'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRewardsRouteImport } from './routes/_authenticated/admin.rewards'
import { Route as AuthenticatedAdminPlacementsRouteImport } from './routes/_authenticated/admin.placements'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminLlmRouteImport } from './routes/_authenticated/admin.llm'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminHeatRouteImport } from './routes/_authenticated/admin.heat'
import { Route as AuthenticatedAdminCharactersRouteImport } from './routes/_authenticated/admin.characters'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedPlayUserIdRouteImport } from './routes/_authenticated/play.user.$id'
import { Route as AuthenticatedChatsStoryIdCharacterIdRouteImport } from './routes/_authenticated/chats.$storyId.$characterId'
import { Route as AuthenticatedAdminStoriesIdRouteImport } from './routes/_authenticated/admin.stories.$id'
import { Route as AuthenticatedAdminStoriesIdPreviewRouteImport } from './routes/_authenticated/admin.stories.$id.preview'
import { Route as AuthenticatedAdminStoriesIdComposeRouteImport } from './routes/_authenticated/admin.stories.$id.compose'
import { Route as AuthenticatedAdminStoriesIdBlocksRouteImport } from './routes/_authenticated/admin.stories.$id.blocks'
import { Route as AuthenticatedAdminStoriesIdChapterChapterIdRouteImport } from './routes/_authenticated/admin.stories.$id.chapter.$chapterId'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveRpgRoute = InteractiveRpgRouteImport.update({
  id: '/interactive-rpg',
  path: '/interactive-rpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRpgIdRoute = StoryRpgIdRouteImport.update({
  id: '/story-rpg/$id',
  path: '/story-rpg/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySessionIdRoute = PlaySessionIdRouteImport.update({
  id: '/play/$sessionId',
  path: '/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveRpgIdRoute = InteractiveRpgIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InteractiveRpgRoute,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlocksRoute = ApiUnlocksRouteImport.update({
  id: '/api/unlocks',
  path: '/api/unlocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryWritingAssistRoute = ApiStoryWritingAssistRouteImport.update({
  id: '/api/story-writing-assist',
  path: '/api/story-writing-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryRpgRoute = ApiStoryRpgRouteImport.update({
  id: '/api/story-rpg',
  path: '/api/story-rpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReaderStoryRoute = ApiReaderStoryRouteImport.update({
  id: '/api/reader-story',
  path: '/api/reader-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReaderProfileImageRoute = ApiReaderProfileImageRouteImport.update({
  id: '/api/reader-profile-image',
  path: '/api/reader-profile-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyChatCharacterRoute = ApiMyChatCharacterRouteImport.update({
  id: '/api/my-chat-character',
  path: '/api/my-chat-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceRoute = ApiMarketplaceRouteImport.update({
  id: '/api/marketplace',
  path: '/api/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomePlacementsRoute = ApiHomePlacementsRouteImport.update({
  id: '/api/home-placements',
  path: '/api/home-placements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharacterChatRoute = ApiCharacterChatRouteImport.update({
  id: '/api/character-chat',
  path: '/api/character-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiStorageEnsureStoryMediaRoute =
  ApiStorageEnsureStoryMediaRouteImport.update({
    id: '/api/storage/ensure-story-media',
    path: '/api/storage/ensure-story-media',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStaffAccessRoute = ApiAuthStaffAccessRouteImport.update({
  id: '/api/auth/staff-access',
  path: '/api/auth/staff-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStoryAiRoute = ApiAdminStoryAiRouteImport.update({
  id: '/api/admin/story-ai',
  path: '/api/admin/story-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStoriesRoute = ApiAdminStoriesRouteImport.update({
  id: '/api/admin/stories',
  path: '/api/admin/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStaffRoute = ApiAdminStaffRouteImport.update({
  id: '/api/admin/staff',
  path: '/api/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRevenueRulesRoute = ApiAdminRevenueRulesRouteImport.update({
  id: '/api/admin/revenue-rules',
  path: '/api/admin/revenue-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlacementsRoute = ApiAdminPlacementsRouteImport.update({
  id: '/api/admin/placements',
  path: '/api/admin/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaRoute = ApiAdminMediaRouteImport.update({
  id: '/api/admin/media',
  path: '/api/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLlmProvidersRoute = ApiAdminLlmProvidersRouteImport.update({
  id: '/api/admin/llm-providers',
  path: '/api/admin/llm-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportSummaryRoute = ApiAdminImportSummaryRouteImport.update({
  id: '/api/admin/import-summary',
  path: '/api/admin/import-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCoreRoute = ApiAdminCoreRouteImport.update({
  id: '/api/admin/core',
  path: '/api/admin/core',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketplaceIdRoute =
  AuthenticatedMarketplaceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedBuilderIdRoute = AuthenticatedBuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBuilderRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStudioRoute =
  AuthenticatedAdminStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStoryRpgRoute =
  AuthenticatedAdminStoryRpgRouteImport.update({
    id: '/story-rpg',
    path: '/story-rpg',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStoriesRoute =
  AuthenticatedAdminStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRewardsRoute =
  AuthenticatedAdminRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlacementsRoute =
  AuthenticatedAdminPlacementsRouteImport.update({
    id: '/placements',
    path: '/placements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLlmRoute = AuthenticatedAdminLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeatRoute = AuthenticatedAdminHeatRouteImport.update({
  id: '/heat',
  path: '/heat',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCharactersRoute =
  AuthenticatedAdminCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPlayUserIdRoute = AuthenticatedPlayUserIdRouteImport.update({
  id: '/play/user/$id',
  path: '/play/user/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsStoryIdCharacterIdRoute =
  AuthenticatedChatsStoryIdCharacterIdRouteImport.update({
    id: '/chats/$storyId/$characterId',
    path: '/chats/$storyId/$characterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoriesIdRoute =
  AuthenticatedAdminStoriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminStoriesRoute,
  } as any)
const AuthenticatedAdminStoriesIdPreviewRoute =
  AuthenticatedAdminStoriesIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAdminStoriesIdRoute,
  } as any)
const AuthenticatedAdminStoriesIdComposeRoute =
  AuthenticatedAdminStoriesIdComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => AuthenticatedAdminStoriesIdRoute,
  } as any)
const AuthenticatedAdminStoriesIdBlocksRoute =
  AuthenticatedAdminStoriesIdBlocksRouteImport.update({
    id: '/blocks',
    path: '/blocks',
    getParentRoute: () => AuthenticatedAdminStoriesIdRoute,
  } as any)
const AuthenticatedAdminStoriesIdChapterChapterIdRoute =
  AuthenticatedAdminStoriesIdChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => AuthenticatedAdminStoriesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/interactive-rpg': typeof InteractiveRpgRouteWithChildren
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/home-placements': typeof ApiHomePlacementsRoute
  '/api/marketplace': typeof ApiMarketplaceRoute
  '/api/my-chat-character': typeof ApiMyChatCharacterRoute
  '/api/reader-profile-image': typeof ApiReaderProfileImageRoute
  '/api/reader-story': typeof ApiReaderStoryRoute
  '/api/story-rpg': typeof ApiStoryRpgRoute
  '/api/story-writing-assist': typeof ApiStoryWritingAssistRoute
  '/api/unlocks': typeof ApiUnlocksRoute
  '/character/$id': typeof CharacterIdRoute
  '/interactive-rpg/$id': typeof InteractiveRpgIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/story-rpg/$id': typeof StoryRpgIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/characters': typeof AuthenticatedAdminCharactersRoute
  '/admin/heat': typeof AuthenticatedAdminHeatRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/llm': typeof AuthenticatedAdminLlmRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRouteWithChildren
  '/admin/story-rpg': typeof AuthenticatedAdminStoryRpgRoute
  '/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/api/admin/core': typeof ApiAdminCoreRoute
  '/api/admin/import-summary': typeof ApiAdminImportSummaryRoute
  '/api/admin/llm-providers': typeof ApiAdminLlmProvidersRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/placements': typeof ApiAdminPlacementsRoute
  '/api/admin/revenue-rules': typeof ApiAdminRevenueRulesRoute
  '/api/admin/staff': typeof ApiAdminStaffRoute
  '/api/admin/stories': typeof ApiAdminStoriesRoute
  '/api/admin/story-ai': typeof ApiAdminStoryAiRoute
  '/api/auth/staff-access': typeof ApiAuthStaffAccessRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/storage/ensure-story-media': typeof ApiStorageEnsureStoryMediaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/stories/$id': typeof AuthenticatedAdminStoriesIdRouteWithChildren
  '/chats/$storyId/$characterId': typeof AuthenticatedChatsStoryIdCharacterIdRoute
  '/play/user/$id': typeof AuthenticatedPlayUserIdRoute
  '/admin/stories/$id/blocks': typeof AuthenticatedAdminStoriesIdBlocksRoute
  '/admin/stories/$id/compose': typeof AuthenticatedAdminStoriesIdComposeRoute
  '/admin/stories/$id/preview': typeof AuthenticatedAdminStoriesIdPreviewRoute
  '/admin/stories/$id/chapter/$chapterId': typeof AuthenticatedAdminStoriesIdChapterChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/interactive-rpg': typeof InteractiveRpgRouteWithChildren
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/home-placements': typeof ApiHomePlacementsRoute
  '/api/marketplace': typeof ApiMarketplaceRoute
  '/api/my-chat-character': typeof ApiMyChatCharacterRoute
  '/api/reader-profile-image': typeof ApiReaderProfileImageRoute
  '/api/reader-story': typeof ApiReaderStoryRoute
  '/api/story-rpg': typeof ApiStoryRpgRoute
  '/api/story-writing-assist': typeof ApiStoryWritingAssistRoute
  '/api/unlocks': typeof ApiUnlocksRoute
  '/character/$id': typeof CharacterIdRoute
  '/interactive-rpg/$id': typeof InteractiveRpgIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/story-rpg/$id': typeof StoryRpgIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/characters': typeof AuthenticatedAdminCharactersRoute
  '/admin/heat': typeof AuthenticatedAdminHeatRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/llm': typeof AuthenticatedAdminLlmRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRouteWithChildren
  '/admin/story-rpg': typeof AuthenticatedAdminStoryRpgRoute
  '/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/api/admin/core': typeof ApiAdminCoreRoute
  '/api/admin/import-summary': typeof ApiAdminImportSummaryRoute
  '/api/admin/llm-providers': typeof ApiAdminLlmProvidersRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/placements': typeof ApiAdminPlacementsRoute
  '/api/admin/revenue-rules': typeof ApiAdminRevenueRulesRoute
  '/api/admin/staff': typeof ApiAdminStaffRoute
  '/api/admin/stories': typeof ApiAdminStoriesRoute
  '/api/admin/story-ai': typeof ApiAdminStoryAiRoute
  '/api/auth/staff-access': typeof ApiAuthStaffAccessRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/storage/ensure-story-media': typeof ApiStorageEnsureStoryMediaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/stories/$id': typeof AuthenticatedAdminStoriesIdRouteWithChildren
  '/chats/$storyId/$characterId': typeof AuthenticatedChatsStoryIdCharacterIdRoute
  '/play/user/$id': typeof AuthenticatedPlayUserIdRoute
  '/admin/stories/$id/blocks': typeof AuthenticatedAdminStoriesIdBlocksRoute
  '/admin/stories/$id/compose': typeof AuthenticatedAdminStoriesIdComposeRoute
  '/admin/stories/$id/preview': typeof AuthenticatedAdminStoriesIdPreviewRoute
  '/admin/stories/$id/chapter/$chapterId': typeof AuthenticatedAdminStoriesIdChapterChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/interactive-rpg': typeof InteractiveRpgRouteWithChildren
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/home-placements': typeof ApiHomePlacementsRoute
  '/api/marketplace': typeof ApiMarketplaceRoute
  '/api/my-chat-character': typeof ApiMyChatCharacterRoute
  '/api/reader-profile-image': typeof ApiReaderProfileImageRoute
  '/api/reader-story': typeof ApiReaderStoryRoute
  '/api/story-rpg': typeof ApiStoryRpgRoute
  '/api/story-writing-assist': typeof ApiStoryWritingAssistRoute
  '/api/unlocks': typeof ApiUnlocksRoute
  '/character/$id': typeof CharacterIdRoute
  '/interactive-rpg/$id': typeof InteractiveRpgIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/story-rpg/$id': typeof StoryRpgIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/characters': typeof AuthenticatedAdminCharactersRoute
  '/_authenticated/admin/heat': typeof AuthenticatedAdminHeatRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/llm': typeof AuthenticatedAdminLlmRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/_authenticated/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stories': typeof AuthenticatedAdminStoriesRouteWithChildren
  '/_authenticated/admin/story-rpg': typeof AuthenticatedAdminStoryRpgRoute
  '/_authenticated/admin/studio': typeof AuthenticatedAdminStudioRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/_authenticated/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/api/admin/core': typeof ApiAdminCoreRoute
  '/api/admin/import-summary': typeof ApiAdminImportSummaryRoute
  '/api/admin/llm-providers': typeof ApiAdminLlmProvidersRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/placements': typeof ApiAdminPlacementsRoute
  '/api/admin/revenue-rules': typeof ApiAdminRevenueRulesRoute
  '/api/admin/staff': typeof ApiAdminStaffRoute
  '/api/admin/stories': typeof ApiAdminStoriesRoute
  '/api/admin/story-ai': typeof ApiAdminStoryAiRoute
  '/api/auth/staff-access': typeof ApiAuthStaffAccessRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/storage/ensure-story-media': typeof ApiStorageEnsureStoryMediaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/stories/$id': typeof AuthenticatedAdminStoriesIdRouteWithChildren
  '/_authenticated/chats/$storyId/$characterId': typeof AuthenticatedChatsStoryIdCharacterIdRoute
  '/_authenticated/play/user/$id': typeof AuthenticatedPlayUserIdRoute
  '/_authenticated/admin/stories/$id/blocks': typeof AuthenticatedAdminStoriesIdBlocksRoute
  '/_authenticated/admin/stories/$id/compose': typeof AuthenticatedAdminStoriesIdComposeRoute
  '/_authenticated/admin/stories/$id/preview': typeof AuthenticatedAdminStoriesIdPreviewRoute
  '/_authenticated/admin/stories/$id/chapter/$chapterId': typeof AuthenticatedAdminStoriesIdChapterChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/explore'
    | '/interactive-rpg'
    | '/premium'
    | '/profile'
    | '/rewards'
    | '/admin'
    | '/builder'
    | '/library'
    | '/marketplace'
    | '/orders'
    | '/api/activity'
    | '/api/character-chat'
    | '/api/chat'
    | '/api/home-placements'
    | '/api/marketplace'
    | '/api/my-chat-character'
    | '/api/reader-profile-image'
    | '/api/reader-story'
    | '/api/story-rpg'
    | '/api/story-writing-assist'
    | '/api/unlocks'
    | '/character/$id'
    | '/interactive-rpg/$id'
    | '/play/$sessionId'
    | '/story-rpg/$id'
    | '/admin/analytics'
    | '/admin/characters'
    | '/admin/heat'
    | '/admin/import'
    | '/admin/llm'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/placements'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/story-rpg'
    | '/admin/studio'
    | '/admin/users'
    | '/builder/$id'
    | '/marketplace/$id'
    | '/api/admin/core'
    | '/api/admin/import-summary'
    | '/api/admin/llm-providers'
    | '/api/admin/media'
    | '/api/admin/placements'
    | '/api/admin/revenue-rules'
    | '/api/admin/staff'
    | '/api/admin/stories'
    | '/api/admin/story-ai'
    | '/api/auth/staff-access'
    | '/api/public/bootstrap-admin'
    | '/api/storage/ensure-story-media'
    | '/admin/'
    | '/admin/stories/$id'
    | '/chats/$storyId/$characterId'
    | '/play/user/$id'
    | '/admin/stories/$id/blocks'
    | '/admin/stories/$id/compose'
    | '/admin/stories/$id/preview'
    | '/admin/stories/$id/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/explore'
    | '/interactive-rpg'
    | '/premium'
    | '/profile'
    | '/rewards'
    | '/builder'
    | '/library'
    | '/marketplace'
    | '/orders'
    | '/api/activity'
    | '/api/character-chat'
    | '/api/chat'
    | '/api/home-placements'
    | '/api/marketplace'
    | '/api/my-chat-character'
    | '/api/reader-profile-image'
    | '/api/reader-story'
    | '/api/story-rpg'
    | '/api/story-writing-assist'
    | '/api/unlocks'
    | '/character/$id'
    | '/interactive-rpg/$id'
    | '/play/$sessionId'
    | '/story-rpg/$id'
    | '/admin/analytics'
    | '/admin/characters'
    | '/admin/heat'
    | '/admin/import'
    | '/admin/llm'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/placements'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/story-rpg'
    | '/admin/studio'
    | '/admin/users'
    | '/builder/$id'
    | '/marketplace/$id'
    | '/api/admin/core'
    | '/api/admin/import-summary'
    | '/api/admin/llm-providers'
    | '/api/admin/media'
    | '/api/admin/placements'
    | '/api/admin/revenue-rules'
    | '/api/admin/staff'
    | '/api/admin/stories'
    | '/api/admin/story-ai'
    | '/api/auth/staff-access'
    | '/api/public/bootstrap-admin'
    | '/api/storage/ensure-story-media'
    | '/admin'
    | '/admin/stories/$id'
    | '/chats/$storyId/$characterId'
    | '/play/user/$id'
    | '/admin/stories/$id/blocks'
    | '/admin/stories/$id/compose'
    | '/admin/stories/$id/preview'
    | '/admin/stories/$id/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chats'
    | '/create'
    | '/explore'
    | '/interactive-rpg'
    | '/premium'
    | '/profile'
    | '/rewards'
    | '/_authenticated/admin'
    | '/_authenticated/builder'
    | '/_authenticated/library'
    | '/_authenticated/marketplace'
    | '/_authenticated/orders'
    | '/api/activity'
    | '/api/character-chat'
    | '/api/chat'
    | '/api/home-placements'
    | '/api/marketplace'
    | '/api/my-chat-character'
    | '/api/reader-profile-image'
    | '/api/reader-story'
    | '/api/story-rpg'
    | '/api/story-writing-assist'
    | '/api/unlocks'
    | '/character/$id'
    | '/interactive-rpg/$id'
    | '/play/$sessionId'
    | '/story-rpg/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/characters'
    | '/_authenticated/admin/heat'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/llm'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/placements'
    | '/_authenticated/admin/rewards'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stories'
    | '/_authenticated/admin/story-rpg'
    | '/_authenticated/admin/studio'
    | '/_authenticated/admin/users'
    | '/_authenticated/builder/$id'
    | '/_authenticated/marketplace/$id'
    | '/api/admin/core'
    | '/api/admin/import-summary'
    | '/api/admin/llm-providers'
    | '/api/admin/media'
    | '/api/admin/placements'
    | '/api/admin/revenue-rules'
    | '/api/admin/staff'
    | '/api/admin/stories'
    | '/api/admin/story-ai'
    | '/api/auth/staff-access'
    | '/api/public/bootstrap-admin'
    | '/api/storage/ensure-story-media'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/stories/$id'
    | '/_authenticated/chats/$storyId/$characterId'
    | '/_authenticated/play/user/$id'
    | '/_authenticated/admin/stories/$id/blocks'
    | '/_authenticated/admin/stories/$id/compose'
    | '/_authenticated/admin/stories/$id/preview'
    | '/_authenticated/admin/stories/$id/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  InteractiveRpgRoute: typeof InteractiveRpgRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiCharacterChatRoute: typeof ApiCharacterChatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHomePlacementsRoute: typeof ApiHomePlacementsRoute
  ApiMarketplaceRoute: typeof ApiMarketplaceRoute
  ApiMyChatCharacterRoute: typeof ApiMyChatCharacterRoute
  ApiReaderProfileImageRoute: typeof ApiReaderProfileImageRoute
  ApiReaderStoryRoute: typeof ApiReaderStoryRoute
  ApiStoryRpgRoute: typeof ApiStoryRpgRoute
  ApiStoryWritingAssistRoute: typeof ApiStoryWritingAssistRoute
  ApiUnlocksRoute: typeof ApiUnlocksRoute
  CharacterIdRoute: typeof CharacterIdRoute
  PlaySessionIdRoute: typeof PlaySessionIdRoute
  StoryRpgIdRoute: typeof StoryRpgIdRoute
  ApiAdminCoreRoute: typeof ApiAdminCoreRoute
  ApiAdminImportSummaryRoute: typeof ApiAdminImportSummaryRoute
  ApiAdminLlmProvidersRoute: typeof ApiAdminLlmProvidersRoute
  ApiAdminMediaRoute: typeof ApiAdminMediaRoute
  ApiAdminPlacementsRoute: typeof ApiAdminPlacementsRoute
  ApiAdminRevenueRulesRoute: typeof ApiAdminRevenueRulesRoute
  ApiAdminStaffRoute: typeof ApiAdminStaffRoute
  ApiAdminStoriesRoute: typeof ApiAdminStoriesRoute
  ApiAdminStoryAiRoute: typeof ApiAdminStoryAiRoute
  ApiAuthStaffAccessRoute: typeof ApiAuthStaffAccessRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiStorageEnsureStoryMediaRoute: typeof ApiStorageEnsureStoryMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-rpg': {
      id: '/interactive-rpg'
      path: '/interactive-rpg'
      fullPath: '/interactive-rpg'
      preLoaderRoute: typeof InteractiveRpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-rpg/$id': {
      id: '/story-rpg/$id'
      path: '/story-rpg/$id'
      fullPath: '/story-rpg/$id'
      preLoaderRoute: typeof StoryRpgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sessionId': {
      id: '/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof PlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-rpg/$id': {
      id: '/interactive-rpg/$id'
      path: '/$id'
      fullPath: '/interactive-rpg/$id'
      preLoaderRoute: typeof InteractiveRpgIdRouteImport
      parentRoute: typeof InteractiveRpgRoute
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlocks': {
      id: '/api/unlocks'
      path: '/api/unlocks'
      fullPath: '/api/unlocks'
      preLoaderRoute: typeof ApiUnlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-writing-assist': {
      id: '/api/story-writing-assist'
      path: '/api/story-writing-assist'
      fullPath: '/api/story-writing-assist'
      preLoaderRoute: typeof ApiStoryWritingAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-rpg': {
      id: '/api/story-rpg'
      path: '/api/story-rpg'
      fullPath: '/api/story-rpg'
      preLoaderRoute: typeof ApiStoryRpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reader-story': {
      id: '/api/reader-story'
      path: '/api/reader-story'
      fullPath: '/api/reader-story'
      preLoaderRoute: typeof ApiReaderStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reader-profile-image': {
      id: '/api/reader-profile-image'
      path: '/api/reader-profile-image'
      fullPath: '/api/reader-profile-image'
      preLoaderRoute: typeof ApiReaderProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-chat-character': {
      id: '/api/my-chat-character'
      path: '/api/my-chat-character'
      fullPath: '/api/my-chat-character'
      preLoaderRoute: typeof ApiMyChatCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace': {
      id: '/api/marketplace'
      path: '/api/marketplace'
      fullPath: '/api/marketplace'
      preLoaderRoute: typeof ApiMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home-placements': {
      id: '/api/home-placements'
      path: '/api/home-placements'
      fullPath: '/api/home-placements'
      preLoaderRoute: typeof ApiHomePlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/character-chat': {
      id: '/api/character-chat'
      path: '/api/character-chat'
      fullPath: '/api/character-chat'
      preLoaderRoute: typeof ApiCharacterChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/storage/ensure-story-media': {
      id: '/api/storage/ensure-story-media'
      path: '/api/storage/ensure-story-media'
      fullPath: '/api/storage/ensure-story-media'
      preLoaderRoute: typeof ApiStorageEnsureStoryMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/staff-access': {
      id: '/api/auth/staff-access'
      path: '/api/auth/staff-access'
      fullPath: '/api/auth/staff-access'
      preLoaderRoute: typeof ApiAuthStaffAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/story-ai': {
      id: '/api/admin/story-ai'
      path: '/api/admin/story-ai'
      fullPath: '/api/admin/story-ai'
      preLoaderRoute: typeof ApiAdminStoryAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stories': {
      id: '/api/admin/stories'
      path: '/api/admin/stories'
      fullPath: '/api/admin/stories'
      preLoaderRoute: typeof ApiAdminStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/staff': {
      id: '/api/admin/staff'
      path: '/api/admin/staff'
      fullPath: '/api/admin/staff'
      preLoaderRoute: typeof ApiAdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/revenue-rules': {
      id: '/api/admin/revenue-rules'
      path: '/api/admin/revenue-rules'
      fullPath: '/api/admin/revenue-rules'
      preLoaderRoute: typeof ApiAdminRevenueRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/placements': {
      id: '/api/admin/placements'
      path: '/api/admin/placements'
      fullPath: '/api/admin/placements'
      preLoaderRoute: typeof ApiAdminPlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media': {
      id: '/api/admin/media'
      path: '/api/admin/media'
      fullPath: '/api/admin/media'
      preLoaderRoute: typeof ApiAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/llm-providers': {
      id: '/api/admin/llm-providers'
      path: '/api/admin/llm-providers'
      fullPath: '/api/admin/llm-providers'
      preLoaderRoute: typeof ApiAdminLlmProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/import-summary': {
      id: '/api/admin/import-summary'
      path: '/api/admin/import-summary'
      fullPath: '/api/admin/import-summary'
      preLoaderRoute: typeof ApiAdminImportSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/core': {
      id: '/api/admin/core'
      path: '/api/admin/core'
      fullPath: '/api/admin/core'
      preLoaderRoute: typeof ApiAdminCoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/$id': {
      id: '/_authenticated/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof AuthenticatedMarketplaceIdRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/builder/$id': {
      id: '/_authenticated/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof AuthenticatedBuilderIdRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/studio': {
      id: '/_authenticated/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AuthenticatedAdminStudioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/story-rpg': {
      id: '/_authenticated/admin/story-rpg'
      path: '/story-rpg'
      fullPath: '/admin/story-rpg'
      preLoaderRoute: typeof AuthenticatedAdminStoryRpgRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stories': {
      id: '/_authenticated/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AuthenticatedAdminStoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rewards': {
      id: '/_authenticated/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AuthenticatedAdminRewardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/placements': {
      id: '/_authenticated/admin/placements'
      path: '/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AuthenticatedAdminPlacementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/llm': {
      id: '/_authenticated/admin/llm'
      path: '/llm'
      fullPath: '/admin/llm'
      preLoaderRoute: typeof AuthenticatedAdminLlmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/heat': {
      id: '/_authenticated/admin/heat'
      path: '/heat'
      fullPath: '/admin/heat'
      preLoaderRoute: typeof AuthenticatedAdminHeatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/characters': {
      id: '/_authenticated/admin/characters'
      path: '/characters'
      fullPath: '/admin/characters'
      preLoaderRoute: typeof AuthenticatedAdminCharactersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/play/user/$id': {
      id: '/_authenticated/play/user/$id'
      path: '/play/user/$id'
      fullPath: '/play/user/$id'
      preLoaderRoute: typeof AuthenticatedPlayUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/$storyId/$characterId': {
      id: '/_authenticated/chats/$storyId/$characterId'
      path: '/chats/$storyId/$characterId'
      fullPath: '/chats/$storyId/$characterId'
      preLoaderRoute: typeof AuthenticatedChatsStoryIdCharacterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/stories/$id': {
      id: '/_authenticated/admin/stories/$id'
      path: '/$id'
      fullPath: '/admin/stories/$id'
      preLoaderRoute: typeof AuthenticatedAdminStoriesIdRouteImport
      parentRoute: typeof AuthenticatedAdminStoriesRoute
    }
    '/_authenticated/admin/stories/$id/preview': {
      id: '/_authenticated/admin/stories/$id/preview'
      path: '/preview'
      fullPath: '/admin/stories/$id/preview'
      preLoaderRoute: typeof AuthenticatedAdminStoriesIdPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminStoriesIdRoute
    }
    '/_authenticated/admin/stories/$id/compose': {
      id: '/_authenticated/admin/stories/$id/compose'
      path: '/compose'
      fullPath: '/admin/stories/$id/compose'
      preLoaderRoute: typeof AuthenticatedAdminStoriesIdComposeRouteImport
      parentRoute: typeof AuthenticatedAdminStoriesIdRoute
    }
    '/_authenticated/admin/stories/$id/blocks': {
      id: '/_authenticated/admin/stories/$id/blocks'
      path: '/blocks'
      fullPath: '/admin/stories/$id/blocks'
      preLoaderRoute: typeof AuthenticatedAdminStoriesIdBlocksRouteImport
      parentRoute: typeof AuthenticatedAdminStoriesIdRoute
    }
    '/_authenticated/admin/stories/$id/chapter/$chapterId': {
      id: '/_authenticated/admin/stories/$id/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/admin/stories/$id/chapter/$chapterId'
      preLoaderRoute: typeof AuthenticatedAdminStoriesIdChapterChapterIdRouteImport
      parentRoute: typeof AuthenticatedAdminStoriesIdRoute
    }
  }
}

interface AuthenticatedAdminStoriesIdRouteChildren {
  AuthenticatedAdminStoriesIdBlocksRoute: typeof AuthenticatedAdminStoriesIdBlocksRoute
  AuthenticatedAdminStoriesIdComposeRoute: typeof AuthenticatedAdminStoriesIdComposeRoute
  AuthenticatedAdminStoriesIdPreviewRoute: typeof AuthenticatedAdminStoriesIdPreviewRoute
  AuthenticatedAdminStoriesIdChapterChapterIdRoute: typeof AuthenticatedAdminStoriesIdChapterChapterIdRoute
}

const AuthenticatedAdminStoriesIdRouteChildren: AuthenticatedAdminStoriesIdRouteChildren =
  {
    AuthenticatedAdminStoriesIdBlocksRoute:
      AuthenticatedAdminStoriesIdBlocksRoute,
    AuthenticatedAdminStoriesIdComposeRoute:
      AuthenticatedAdminStoriesIdComposeRoute,
    AuthenticatedAdminStoriesIdPreviewRoute:
      AuthenticatedAdminStoriesIdPreviewRoute,
    AuthenticatedAdminStoriesIdChapterChapterIdRoute:
      AuthenticatedAdminStoriesIdChapterChapterIdRoute,
  }

const AuthenticatedAdminStoriesIdRouteWithChildren =
  AuthenticatedAdminStoriesIdRoute._addFileChildren(
    AuthenticatedAdminStoriesIdRouteChildren,
  )

interface AuthenticatedAdminStoriesRouteChildren {
  AuthenticatedAdminStoriesIdRoute: typeof AuthenticatedAdminStoriesIdRouteWithChildren
}

const AuthenticatedAdminStoriesRouteChildren: AuthenticatedAdminStoriesRouteChildren =
  {
    AuthenticatedAdminStoriesIdRoute:
      AuthenticatedAdminStoriesIdRouteWithChildren,
  }

const AuthenticatedAdminStoriesRouteWithChildren =
  AuthenticatedAdminStoriesRoute._addFileChildren(
    AuthenticatedAdminStoriesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCharactersRoute: typeof AuthenticatedAdminCharactersRoute
  AuthenticatedAdminHeatRoute: typeof AuthenticatedAdminHeatRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminLlmRoute: typeof AuthenticatedAdminLlmRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPlacementsRoute: typeof AuthenticatedAdminPlacementsRoute
  AuthenticatedAdminRewardsRoute: typeof AuthenticatedAdminRewardsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStoriesRoute: typeof AuthenticatedAdminStoriesRouteWithChildren
  AuthenticatedAdminStoryRpgRoute: typeof AuthenticatedAdminStoryRpgRoute
  AuthenticatedAdminStudioRoute: typeof AuthenticatedAdminStudioRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCharactersRoute: AuthenticatedAdminCharactersRoute,
  AuthenticatedAdminHeatRoute: AuthenticatedAdminHeatRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminLlmRoute: AuthenticatedAdminLlmRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPlacementsRoute: AuthenticatedAdminPlacementsRoute,
  AuthenticatedAdminRewardsRoute: AuthenticatedAdminRewardsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStoriesRoute: AuthenticatedAdminStoriesRouteWithChildren,
  AuthenticatedAdminStoryRpgRoute: AuthenticatedAdminStoryRpgRoute,
  AuthenticatedAdminStudioRoute: AuthenticatedAdminStudioRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBuilderRouteChildren {
  AuthenticatedBuilderIdRoute: typeof AuthenticatedBuilderIdRoute
}

const AuthenticatedBuilderRouteChildren: AuthenticatedBuilderRouteChildren = {
  AuthenticatedBuilderIdRoute: AuthenticatedBuilderIdRoute,
}

const AuthenticatedBuilderRouteWithChildren =
  AuthenticatedBuilderRoute._addFileChildren(AuthenticatedBuilderRouteChildren)

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceIdRoute: typeof AuthenticatedMarketplaceIdRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceIdRoute: AuthenticatedMarketplaceIdRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRouteWithChildren
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedChatsStoryIdCharacterIdRoute: typeof AuthenticatedChatsStoryIdCharacterIdRoute
  AuthenticatedPlayUserIdRoute: typeof AuthenticatedPlayUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBuilderRoute: AuthenticatedBuilderRouteWithChildren,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedChatsStoryIdCharacterIdRoute:
    AuthenticatedChatsStoryIdCharacterIdRoute,
  AuthenticatedPlayUserIdRoute: AuthenticatedPlayUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface InteractiveRpgRouteChildren {
  InteractiveRpgIdRoute: typeof InteractiveRpgIdRoute
}

const InteractiveRpgRouteChildren: InteractiveRpgRouteChildren = {
  InteractiveRpgIdRoute: InteractiveRpgIdRoute,
}

const InteractiveRpgRouteWithChildren = InteractiveRpgRoute._addFileChildren(
  InteractiveRpgRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  InteractiveRpgRoute: InteractiveRpgRouteWithChildren,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiCharacterChatRoute: ApiCharacterChatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHomePlacementsRoute: ApiHomePlacementsRoute,
  ApiMarketplaceRoute: ApiMarketplaceRoute,
  ApiMyChatCharacterRoute: ApiMyChatCharacterRoute,
  ApiReaderProfileImageRoute: ApiReaderProfileImageRoute,
  ApiReaderStoryRoute: ApiReaderStoryRoute,
  ApiStoryRpgRoute: ApiStoryRpgRoute,
  ApiStoryWritingAssistRoute: ApiStoryWritingAssistRoute,
  ApiUnlocksRoute: ApiUnlocksRoute,
  CharacterIdRoute: CharacterIdRoute,
  PlaySessionIdRoute: PlaySessionIdRoute,
  StoryRpgIdRoute: StoryRpgIdRoute,
  ApiAdminCoreRoute: ApiAdminCoreRoute,
  ApiAdminImportSummaryRoute: ApiAdminImportSummaryRoute,
  ApiAdminLlmProvidersRoute: ApiAdminLlmProvidersRoute,
  ApiAdminMediaRoute: ApiAdminMediaRoute,
  ApiAdminPlacementsRoute: ApiAdminPlacementsRoute,
  ApiAdminRevenueRulesRoute: ApiAdminRevenueRulesRoute,
  ApiAdminStaffRoute: ApiAdminStaffRoute,
  ApiAdminStoriesRoute: ApiAdminStoriesRoute,
  ApiAdminStoryAiRoute: ApiAdminStoryAiRoute,
  ApiAuthStaffAccessRoute: ApiAuthStaffAccessRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiStorageEnsureStoryMediaRoute: ApiStorageEnsureStoryMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
