// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { getFreshAccessToken } from '@/lib/supabase-auth-fetch'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const token = await getFreshAccessToken().catch(async () => {
      const { data } = await supabase.auth.getSession()
      return data.session?.access_token
    })
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
